<?php

namespace Database\Seeders;

use App\Models\Application;
use App\Models\Attribute;
use App\Models\Category;
use App\Models\Product;
use App\Models\SearchSynonym;
use App\Models\SubCategory;
use App\Models\SubCategoryAttribute;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Imports the customer's catalog classifier (12 sections -> groups -> product
 * classes -> attributes) from the committed JSON snapshot generated by
 * `php artisan catalog:generate-classifier-json <xlsx>`.
 *
 * Re-runnable: rows are matched by slug / az-name identity, pivots are pruned
 * to the imported definition, nothing is duplicated on a second run.
 */
class CatalogClassifierSeeder extends Seeder
{
    /**
     * Pre-classifier root categories. They stay in the DB (products may still
     * reference them) but leave the visible catalog tree.
     */
    private const LEGACY_CATEGORY_SLUGS = [
        'kafel', 'dam-ortukleri', 'laminat', 'elektrik', 'santexnika', 'kerpic', 'sement',
    ];

    /**
     * Best-effort remap of demo products: legacy root category slug ->
     * classifier product class (az name). Applied unless a name override matches.
     */
    private const LEGACY_CLASS_MAP = [
        'kafel' => 'Keramoqranit / Keramik plitə / Təbii daş / Mozaika',
        'dam-ortukleri' => 'Dam örtüyü',
        'laminat' => 'Laminat',
        'elektrik' => 'İşıqlandırma cihazı (LED, içəriquraşdırılan/üstəquraşdırılan/trek)',
        'santexnika' => 'Qarışdırıcılar',
        'kerpic' => 'Kərpic',
        'sement' => 'Sement',
    ];

    /** Product-name fragment (az) -> classifier class that fits better than the category default. */
    private const LEGACY_NAME_OVERRIDES = [
        'Bitum' => 'Əridilərək yapışdırılan rulon dam örtüyü (yastı dam)',
    ];

    /** @var array<string, true> */
    private array $categorySlugs = [];

    /** @var array<string, true> */
    private array $subCategorySlugs = [];

    /** @var array<string, true> */
    private array $attributeSlugs = [];

    /** @var array<string, int> dedup identity (name|type|options) -> attribute id */
    private array $attributeRegistry = [];

    public function run(): void
    {
        $path = database_path('seeders/data/catalog_classifier.json');
        if (! File::exists($path)) {
            $this->command?->warn("CatalogClassifierSeeder skipped: {$path} not found.");

            return;
        }

        $data = json_decode(File::get($path), true, 512, JSON_THROW_ON_ERROR);

        DB::transaction(function () use ($data) {
            $this->loadSlugRegistries();
            $applications = $this->seedApplications($data['applications']);
            $this->seedTree($data['sections'], $applications);
            $this->retireLegacyCategories();
            $this->remapLegacyProducts();
        });
    }

    private function loadSlugRegistries(): void
    {
        $this->categorySlugs = array_fill_keys(Category::pluck('slug')->all(), true);
        $this->subCategorySlugs = array_fill_keys(SubCategory::whereNotNull('slug')->pluck('slug')->all(), true);
        $this->attributeSlugs = array_fill_keys(Attribute::pluck('slug')->all(), true);
        $this->applicationSlugs = array_fill_keys(Application::pluck('slug')->all(), true);

        foreach (Attribute::with('options')->get() as $attribute) {
            $this->attributeRegistry[$this->attributeIdentity(
                $attribute->getTranslation('name', 'az'),
                $attribute->field_type->value,
                $attribute->options->map(fn ($o) => $o->getTranslation('value', 'az'))->all(),
            )] = $attribute->id;
        }
    }

    /**
     * @param  list<string>  $names
     * @return array<string, int> az name -> id
     */
    private function seedApplications(array $names): array
    {
        $ids = [];
        foreach ($names as $i => $name) {
            $application = Application::where('name->az', $name)->first();
            if (! $application) {
                $application = Application::create([
                    'name' => $this->tr($name),
                    'slug' => $this->uniqueSlug($name, 'applications'),
                    'sort_order' => $i + 1,
                    'is_active' => true,
                ]);
            }
            $ids[$name] = $application->id;
        }

        return $ids;
    }

    /**
     * @param  array<string, int>  $applicationIds
     */
    private function seedTree(array $sections, array $applicationIds): void
    {
        foreach ($sections as $sectionData) {
            $section = $this->upsertCategory(
                parentId: null,
                name: $sectionData['name'],
                sortOrder: $sectionData['number'],
                showOnHome: true,
            );

            foreach (array_values($sectionData['groups']) as $gi => $groupData) {
                $group = $this->upsertCategory(
                    parentId: $section->id,
                    name: $groupData['name'],
                    sortOrder: $gi + 1,
                    showOnHome: false,
                );

                foreach (array_values($groupData['classes']) as $ci => $classData) {
                    $this->seedClass($group, $classData, $ci + 1, $applicationIds);
                }
            }
        }
    }

    private function upsertCategory(?int $parentId, string $name, int $sortOrder, bool $showOnHome): Category
    {
        $category = Category::where('parent_id', $parentId)->where('name->az', $name)->first();

        if (! $category) {
            $category = new Category([
                'parent_id' => $parentId,
                'slug' => $this->uniqueSlug($name, 'categories'),
            ]);
            $category->setTranslations('name', $this->tr($name));
        }

        $category->fill([
            'sort_order' => $sortOrder,
            'is_active' => true,
            'show_on_home' => $showOnHome,
        ])->save();

        return $category;
    }

    /**
     * @param  array<string, int>  $applicationIds
     */
    private function seedClass(Category $group, array $classData, int $sortOrder, array $applicationIds): void
    {
        $class = SubCategory::where('category_id', $group->id)->where('name->az', $classData['name'])->first();

        if (! $class) {
            $class = new SubCategory([
                'category_id' => $group->id,
                'slug' => $this->uniqueSlug($classData['name'], 'sub_categories'),
            ]);
            $class->setTranslations('name', $this->tr($classData['name']));
        }

        $class->fill(['sort_order' => $sortOrder, 'is_active' => true])->save();

        // Default application tags for this class (sync prunes removed ones).
        $class->applications()->sync(
            collect($classData['applications'])->map(fn ($n) => $applicationIds[$n] ?? null)->filter()->all()
        );

        // Attributes: the class form definition.
        $seededAttributeIds = [];
        foreach ($classData['attributes'] as $row) {
            $attributeId = $this->resolveAttribute($row);
            $seededAttributeIds[] = $attributeId;

            SubCategoryAttribute::updateOrCreate(
                ['sub_category_id' => $class->id, 'attribute_id' => $attributeId],
                [
                    'is_required' => $row['required'],
                    'is_filterable' => $row['filterable'],
                    'filter_priority' => $row['filter_priority'],
                    'unit' => $row['unit'],
                    'sort_order' => $row['sort_order'],
                ],
            );
        }

        SubCategoryAttribute::where('sub_category_id', $class->id)
            ->whereNotIn('attribute_id', $seededAttributeIds)
            ->delete();

        foreach ($classData['synonyms'] as $phrase) {
            SearchSynonym::updateOrCreate(
                ['sub_category_id' => $class->id, 'phrase' => $phrase, 'locale' => 'az'],
            );
        }
    }

    /**
     * Attributes are shared across classes only when name + field type + option
     * set are identical; otherwise each class context gets its own attribute.
     */
    private function resolveAttribute(array $row): int
    {
        $identity = $this->attributeIdentity($row['name'], $row['field_type'], $row['options']);
        if (isset($this->attributeRegistry[$identity])) {
            return $this->attributeRegistry[$identity];
        }

        $attribute = new Attribute([
            'slug' => $this->uniqueSlug($row['name'], 'attributes'),
            'field_type' => $row['field_type'],
            'complexity' => $row['complexity'],
            'is_active' => true,
        ]);
        $attribute->setTranslations('name', $this->tr($row['name']));
        if ($row['tooltip'] !== null) {
            $attribute->setTranslations('tooltip', $this->tr($row['tooltip']));
        }
        $attribute->save();

        $optionSlugs = [];
        foreach ($row['options'] as $i => $value) {
            $slug = Str::slug($value) ?: 'option';
            while (isset($optionSlugs[$slug])) {
                $slug = Str::slug($value).'-'.($i + 1);
            }
            $optionSlugs[$slug] = true;

            $attribute->options()->create([
                'value' => $this->tr($value),
                'slug' => $slug,
                'sort_order' => $i + 1,
            ]);
        }

        return $this->attributeRegistry[$identity] = $attribute->id;
    }

    private function retireLegacyCategories(): void
    {
        Category::whereNull('parent_id')
            ->whereIn('slug', self::LEGACY_CATEGORY_SLUGS)
            ->update(['is_active' => false, 'show_on_home' => false]);
    }

    /**
     * Moves demo products off the retired roots onto a fitting classifier
     * group (category_id) + class (sub_category_id). Products with no mapping
     * stay where they are and are reported for manual remap.
     */
    private function remapLegacyProducts(): void
    {
        $legacyIds = Category::whereIn('slug', self::LEGACY_CATEGORY_SLUGS)->pluck('id', 'slug');

        foreach ($legacyIds as $slug => $categoryId) {
            $products = Product::where('category_id', $categoryId)->get();

            foreach ($products as $product) {
                $className = self::LEGACY_CLASS_MAP[$slug] ?? null;
                foreach (self::LEGACY_NAME_OVERRIDES as $fragment => $overrideClass) {
                    if (str_contains($product->getTranslation('name', 'az'), $fragment)) {
                        $className = $overrideClass;
                    }
                }

                $class = $className
                    ? SubCategory::where('name->az', $className)->first()
                    : null;

                if (! $class) {
                    $this->command?->warn("Product #{$product->id} left on legacy category '{$slug}' — no classifier match.");

                    continue;
                }

                $product->forceFill([
                    'category_id' => $class->category_id,
                    'sub_category_id' => $class->id,
                ])->save();
            }
        }
    }

    /** @return array{az: string, ru: string, en: string} */
    private function tr(string $az): array
    {
        // ru/en start as explicit copies of az so every locale renders; admins translate later.
        return ['az' => $az, 'ru' => $az, 'en' => $az];
    }

    private function uniqueSlug(string $name, string $registry): string
    {
        $base = Str::slug($name) ?: 'item';
        $property = match ($registry) {
            'categories' => 'categorySlugs',
            'sub_categories' => 'subCategorySlugs',
            'attributes' => 'attributeSlugs',
            'applications' => 'applicationSlugs',
        };
        $slugs = &$this->{$property};

        $slug = $base;
        for ($i = 2; isset($slugs[$slug]); $i++) {
            $slug = "{$base}-{$i}";
        }
        $slugs[$slug] = true;

        return $slug;
    }

    /** @var array<string, true> */
    private array $applicationSlugs = [];

    /** @param list<string> $options */
    private function attributeIdentity(string $name, string $fieldType, array $options): string
    {
        return $name.'|'.$fieldType.'|'.implode('||', $options);
    }
}
