// JS entry point (Vite). Shared modules are imported statically; the page module is
// imported dynamically based on <body data-page="...">, so each page ships its own chunk.
// Page agents do not edit this file — all 23 slugs are already registered.

import './shared/navbar.js';
import './shared/cursor.js';

const pages = {
    'home': () => import('./pages/home.js'),
    'catalog': () => import('./pages/catalog.js'),
    'product': () => import('./pages/product.js'),
    'search': () => import('./pages/search.js'),
    'specialists': () => import('./pages/specialists.js'),
    'specialist': () => import('./pages/specialist.js'),
    'blog': () => import('./pages/blog.js'),
    'sell': () => import('./pages/sell.js'),
    'login': () => import('./pages/login.js'),
    'register': () => import('./pages/register.js'),
    'cart': () => import('./pages/cart.js'),
    'calculator': () => import('./pages/calculator.js'),
    'calculator-detailed': () => import('./pages/calculator-detailed.js'),
    'business-register': () => import('./pages/business-register.js'),
    'business-onboarding-step1': () => import('./pages/business-onboarding-step1.js'),
    'business-onboarding-step3': () => import('./pages/business-onboarding-step3.js'),
    'business-profile': () => import('./pages/business-profile.js'),
    'business-profile-company': () => import('./pages/business-profile-company.js'),
    'business-profile-contact': () => import('./pages/business-profile-contact.js'),
    'business-profile-products': () => import('./pages/business-profile-products.js'),
    'business-profile-showrooms': () => import('./pages/business-profile-showrooms.js'),
    'business-profile-notifications': () => import('./pages/business-profile-notifications.js'),
    'business-profile-security': () => import('./pages/business-profile-security.js'),
};

pages[document.body.dataset.page]?.();
