// JS entry point (Vite). Every module is imported statically so Rollup emits a single
// app.js bundle; the page module to run is picked from <body data-page="...">.
// Page agents do not edit this file — all 36 slugs are already registered.

import './shared/navbar.js';
import './shared/cursor.js';
import './shared/login-modal.js';

import home from './pages/home.js';
import catalog from './pages/catalog.js';
import product from './pages/product.js';
import search from './pages/search.js';
import specialists from './pages/specialists.js';
import specialist from './pages/specialist.js';
import blog from './pages/blog.js';
import sell from './pages/sell.js';
import login from './pages/login.js';
import register from './pages/register.js';
import cart from './pages/cart.js';
import calculator from './pages/calculator.js';
import calculatorDetailed from './pages/calculator-detailed.js';
import businessRegister from './pages/business-register.js';
import businessOnboardingStep1 from './pages/business-onboarding-step1.js';
import businessOnboardingStep3 from './pages/business-onboarding-step3.js';
import businessProfile from './pages/business-profile.js';
import businessProfileCompany from './pages/business-profile-company.js';
import businessProfileContact from './pages/business-profile-contact.js';
import businessProfileProducts from './pages/business-profile-products.js';
import businessProfileShowrooms from './pages/business-profile-showrooms.js';
import businessProfileNotifications from './pages/business-profile-notifications.js';
import businessProfileSecurity from './pages/business-profile-security.js';
import businessOrders from './pages/business-orders.js';
import businessProductEdit from './pages/business-product-edit.js';
import businessInventory from './pages/business-inventory.js';

import accountProfile from './pages/account-profile.js';
import accountOrders from './pages/account-orders.js';
import about from './pages/about.js';
import blogArticle from './pages/blog-article.js';
import specialistOwner from './pages/specialist-owner.js';
import specialistOnboarding from './pages/specialist-onboarding.js';
import specialistCabinet from './pages/specialist-cabinet.js';
import specialistCabinetPortfolio from './pages/specialist-cabinet-portfolio.js';
import specialistCabinetServices from './pages/specialist-cabinet-services.js';
import specialistCabinetSchedule from './pages/specialist-cabinet-schedule.js';
import specialistCabinetReviews from './pages/specialist-cabinet-reviews.js';
import specialistCabinetNotifications from './pages/specialist-cabinet-notifications.js';
import specialistCabinetSecurity from './pages/specialist-cabinet-security.js';
import businessOnboardingStep2 from './pages/business-onboarding-step2.js';
import businessOnboardingStep4 from './pages/business-onboarding-step4.js';
import wishlist from './pages/wishlist.js';
import legal from './pages/legal.js';

const pages = {
    'home': home,
    'catalog': catalog,
    'product': product,
    'search': search,
    'specialists': specialists,
    'specialist': specialist,
    'blog': blog,
    'sell': sell,
    'login': login,
    'register': register,
    'cart': cart,
    'calculator': calculator,
    'calculator-detailed': calculatorDetailed,
    'business-register': businessRegister,
    'business-onboarding-step1': businessOnboardingStep1,
    'business-onboarding-step3': businessOnboardingStep3,
    'business-profile': businessProfile,
    'business-profile-company': businessProfileCompany,
    'business-profile-contact': businessProfileContact,
    'business-profile-products': businessProfileProducts,
    'business-profile-showrooms': businessProfileShowrooms,
    'business-profile-notifications': businessProfileNotifications,
    'business-profile-security': businessProfileSecurity,
    'business-orders': businessOrders,
    'business-order-detail': businessOrders,
    'business-product-edit': businessProductEdit,
    'business-inventory': businessInventory,

    'account-profile': accountProfile,
    'account-orders': accountOrders,
    'about': about,
    'blog-article': blogArticle,
    'specialist-owner': specialistOwner,
    'specialist-onboarding': specialistOnboarding,
    'specialist-cabinet': specialistCabinet,
    'specialist-cabinet-portfolio': specialistCabinetPortfolio,
    'specialist-cabinet-services': specialistCabinetServices,
    'specialist-cabinet-schedule': specialistCabinetSchedule,
    'specialist-cabinet-reviews': specialistCabinetReviews,
    'specialist-cabinet-notifications': specialistCabinetNotifications,
    'specialist-cabinet-security': specialistCabinetSecurity,
    'business-onboarding-step2': businessOnboardingStep2,
    'business-onboarding-step4': businessOnboardingStep4,
    'wishlist': wishlist,
    'legal': legal,
};

pages[document.body.dataset.page]?.();
